version: "2"

# TODO: update this config, also in ggsrc.
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - goconst
    - gosec
    - misspell
    - unconvert
  settings:
    dogsled:
      max-blank-identifiers: 3
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -S1039
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
          - gosec
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/one2x-ai/wpgx)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$# Updated for one2x-ai fork
